# fly.toml app configuration file generated for filedrawer-polished-moonrise-2782 on 2026-09-30T23:01:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'filedrawer-polished-moonrise-2782'
primary_region = 'ewr'

[build]
  dockerfile = 'Dockerfile'

[env]
  FD_PUBLIC_URL = 'https://filedrawer-polished-moonrise-2782.fly.dev'
  FD_DATA_DIR = '/data'
  FD_INCLUDE_DRAFTS = '1'

[[mounts]]
  source = 'fd_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
