"""01_tidy: raw export -> data/raw_tidy.csv (identifier columns removed)

Generated by filedrawer 0.1.0. Run from the study folder: python scripts/01_tidy.py
"""
import json
import pathlib
import sys
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")
ROOT = pathlib.Path(__file__).resolve().parents[1]

RAW = ROOT / "raw_export.csv"
DROP = ["StartDate", "EndDate", "IPAddress", "RecordedDate", "ResponseId", "RecipientLastName", "RecipientFirstName", "RecipientEmail", "ExternalReference", "LocationLatitude", "LocationLongitude", "open_comment"]
SKIP = [1, 2]

def main():
    if not RAW.exists():
        print(f"raw export not found at {RAW}; data/raw_tidy.csv is the tidy copy shipped with this package")
        return
    df = pd.read_csv(RAW, skiprows=SKIP or None, dtype=str, keep_default_na=False, encoding="utf-8-sig")
    df = df[[c for c in df.columns if c not in DROP]]
    for c in df.columns:
        s = df[c].replace("", None)
        conv = pd.to_numeric(s, errors="coerce")
        df[c] = conv if s.notna().sum() > 0 and conv.notna().sum() == s.notna().sum() else s
    df.insert(0, "row_id", range(1, len(df) + 1))
    (ROOT / "data").mkdir(exist_ok=True)
    df.to_csv(ROOT / "data" / "raw_tidy.csv", index=False)
    print(f"wrote data/raw_tidy.csv: {len(df)} rows, {df.shape[1]} columns; dropped {len(DROP)} identifier columns")

if __name__ == "__main__":
    main()
