"""02_clean: data/raw_tidy.csv -> data/clean.csv (exclusions, outcomes, treatment indicator)

Generated by filedrawer 0.1.0. Run from the study folder: python scripts/02_clean.py
"""
import json
import pathlib
import sys
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")
ROOT = pathlib.Path(__file__).resolve().parents[1]

OUTCOMES = json.loads("[{\"name\": \"imm_index\", \"label\": \"Pro-immigration attitude index\", \"kind\": \"mean_items\", \"columns\": [\"imm_att_1\", \"imm_att_2\", \"imm_att_3\"], \"reverse\": [\"imm_att_2\"], \"scale\": [1, 7], \"construction\": \"mean of three 7-point items, item 2 reverse coded\"}, {\"name\": \"policy_support\", \"label\": \"Policy attitudes toward immigration\", \"kind\": \"single_item\", \"columns\": [\"policy_support\"], \"reverse\": [], \"scale\": [1, 7], \"construction\": \"single 7-point favor-oppose item\"}]")
EXCLUSIONS = ["Finished == 1"]
ARM_COL = "condition"
TREATED = "treatment"
CONTROL = "control"

def construct(df, o):
    kind = o.get("kind", "mean_items")
    lo, hi = o.get("scale") or [None, None]
    if kind == "single_item":
        return pd.to_numeric(df[o["columns"][0]], errors="coerce")
    if kind == "mean_items":
        parts = []
        for c in o["columns"]:
            s = pd.to_numeric(df[c], errors="coerce")
            if c in (o.get("reverse") or []) and lo is not None:
                s = (lo + hi) - s
            parts.append(s)
        return pd.concat(parts, axis=1).mean(axis=1, skipna=False)
    raise SystemExit(f"outcome {o['name']} has kind={kind}; custom construction must be implemented in this script")

def main():
    df = pd.read_csv(ROOT / "data" / "raw_tidy.csv")
    n0 = len(df)
    for expr in EXCLUSIONS:
        try:
            df = df.query(expr)
        except Exception as e:
            print(f"WARNING: exclusion {expr!r} could not be applied: {e}")
    print(f"sample: {n0} -> {len(df)} after exclusions {EXCLUSIONS}")
    if ARM_COL and ARM_COL in df.columns:
        df = df[df[ARM_COL].isin([TREATED, CONTROL])].copy()
        df["treat"] = (df[ARM_COL].astype(str) == str(TREATED)).astype(int)
        print(f"arms: {df[ARM_COL].value_counts().to_dict()}")
    for o in OUTCOMES:
        df[o["name"]] = construct(df, o)
        print(f"outcome {o['name']}: mean={df[o['name']].mean():.3f} sd={df[o['name']].std():.3f} missing={int(df[o['name']].isna().sum())}")
    (ROOT / "data").mkdir(exist_ok=True)
    df.to_csv(ROOT / "data" / "clean.csv", index=False)
    print(f"wrote data/clean.csv: {len(df)} rows, {df.shape[1]} columns")

if __name__ == "__main__":
    main()
