"""03_registered: registered (and documented-deviation) hypothesis tests

Generated by filedrawer 0.1.0. Run from the study folder: python scripts/03_registered.py
"""
import json
import pathlib
import sys
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")
ROOT = pathlib.Path(__file__).resolve().parents[1]

import statsmodels.formula.api as smf
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HYPOTHESES = json.loads("[{\"id\": \"H1\", \"text\": \"Treatment increases pro-immigration attitudes on the primary index.\", \"outcome\": \"imm_index\", \"treatment\": {\"column\": \"condition\", \"contrast\": [\"treatment\", \"control\"]}, \"direction\": \"positive\", \"estimator\": {\"kind\": \"ols\", \"robust\": \"HC2\", \"cluster\": null, \"covariates\": []}, \"subgroup\": null, \"exclusions\": [\"Finished == 1\"]}, {\"id\": \"H2\", \"text\": \"Treatment increases favorable policy attitudes, adjusting for party identification and age.\", \"outcome\": \"policy_support\", \"treatment\": {\"column\": \"condition\", \"contrast\": [\"treatment\", \"control\"]}, \"direction\": \"positive\", \"estimator\": {\"kind\": \"ols\", \"robust\": \"HC2\", \"cluster\": null, \"covariates\": [\"pid3\", \"agecat\"]}, \"subgroup\": null, \"exclusions\": [\"Finished == 1\"]}]")
SUBGROUPS = json.loads("[{\"id\": \"S1\", \"hypothesis\": \"H1\", \"moderator\": \"pid3\", \"levels\": {\"1\": \"Democrat\", \"2\": \"Republican\"}, \"expected\": \"treatment effect larger among Democrats than Republicans\"}]")
CATEGORICAL = set(["agecat", "attn", "consent", "educ", "gender", "ideo5", "imm_att_1", "imm_att_2", "imm_att_3", "pid3", "policy_support"])
ALPHA = 0.05
RES = ROOT / "results"; FIG = ROOT / "figures"
RES.mkdir(exist_ok=True); FIG.mkdir(exist_ok=True)

def term(c):
    return f"C({c})" if c in CATEGORICAL else c

def fit(df, formula, est):
    kw = {}
    cl = est.get("cluster")
    if cl:
        kw = dict(cov_type="cluster", cov_kwds={"groups": df[cl]})
    else:
        kw = dict(cov_type=est.get("robust") or "HC2")
    return smf.ols(formula, data=df).fit(**kw)

def tidy(res, analysis_id):
    ci = res.conf_int()
    rows = []
    for t in res.params.index:
        rows.append({"analysis_id": analysis_id, "term": t, "estimate": res.params[t], "std_error": res.bse[t],
                     "statistic": res.tvalues[t], "p_value": res.pvalues[t], "conf_low": ci.loc[t, 0], "conf_high": ci.loc[t, 1]})
    return pd.DataFrame(rows)

def supported(est, p, direction):
    if direction == "positive":
        return bool(est > 0 and p < ALPHA)
    if direction == "negative":
        return bool(est < 0 and p < ALPHA)
    return bool(p < ALPHA)

def main():
    df = pd.read_csv(ROOT / "data" / "clean.csv")
    summary = []
    for h in HYPOTHESES:
        d = df.copy()
        for expr in h.get("exclusions") or []:
            try:
                d = d.query(expr)
            except Exception as e:
                print(f"WARNING: {h['id']} exclusion {expr!r} skipped: {e}")
        est = h.get("estimator", {})
        covs = est.get("covariates") or []
        d = d.dropna(subset=[h["outcome"], "treat"] + covs)
        formula = f"{h['outcome']} ~ treat" + "".join(f" + {term(c)}" for c in covs)
        if est.get("kind") == "diff_means":
            formula = f"{h['outcome']} ~ treat"
        res = fit(d, formula, est)
        tidy(res, h["id"]).to_csv(RES / f"{h['id']}.csv", index=False)
        e, se, p = res.params["treat"], res.bse["treat"], res.pvalues["treat"]
        g = d.groupby("treat")[h["outcome"]].agg(["mean", "std", "count"])
        summary.append({"analysis_id": h["id"], "outcome": h["outcome"], "formula": formula, "cov_type": res.cov_type,
                        "estimate": e, "std_error": se, "p_value": p, "n": int(res.nobs),
                        "mean_control": g.loc[0, "mean"] if 0 in g.index else np.nan,
                        "mean_treated": g.loc[1, "mean"] if 1 in g.index else np.nan,
                        "direction": h.get("direction", "two_sided"), "supported": supported(e, p, h.get("direction", "two_sided"))})
        print(f"{h['id']}: {formula} | ATE={e:.3f} (SE {se:.3f}, p={p:.4f}, N={int(res.nobs)})")
    hyps = {h["id"]: h for h in HYPOTHESES}
    for s in SUBGROUPS:
        h = hyps.get(s["hypothesis"])
        if h is None:
            continue
        d = df.copy()
        for expr in h.get("exclusions") or []:
            try:
                d = d.query(expr)
            except Exception:
                pass
        levels = s.get("levels") or {}
        mod = s["moderator"]
        if levels:
            d = d[d[mod].astype(str).isin([str(k) for k in levels])]
        d = d.dropna(subset=[h["outcome"], "treat", mod])
        d["_mod"] = d[mod].astype(str).map({str(k): v for k, v in levels.items()}) if levels else d[mod].astype(str)
        res = fit(d, f"{h['outcome']} ~ treat * C(_mod)", h.get("estimator", {}))
        tidy(res, s["id"]).to_csv(RES / f"{s['id']}.csv", index=False)
        inter = [t for t in res.params.index if t.startswith("treat:")]
        rows = []
        for lvl, sub in d.groupby("_mod"):
            r = fit(sub, f"{h['outcome']} ~ treat", h.get("estimator", {}))
            rows.append({"analysis_id": s["id"], "level": lvl, "estimate": r.params["treat"], "std_error": r.bse["treat"],
                         "p_value": r.pvalues["treat"], "n": int(r.nobs)})
        pd.DataFrame(rows).to_csv(RES / f"{s['id']}_by_level.csv", index=False)
        for t in inter:
            summary.append({"analysis_id": s["id"], "outcome": h["outcome"], "formula": f"{h['outcome']} ~ treat * C({mod})",
                            "cov_type": res.cov_type, "estimate": res.params[t], "std_error": res.bse[t], "p_value": res.pvalues[t],
                            "n": int(res.nobs), "mean_control": np.nan, "mean_treated": np.nan, "direction": "two_sided",
                            "supported": bool(res.pvalues[t] < ALPHA), "term": t})
            print(f"{s['id']}: interaction {t} = {res.params[t]:.3f} (SE {res.bse[t]:.3f}, p={res.pvalues[t]:.4f})")
    pd.DataFrame(summary).to_csv(RES / "registered_summary.csv", index=False)
    # coefficient plot
    main_rows = [r for r in summary if "term" not in r]
    if main_rows:
        fig, ax = plt.subplots(figsize=(6, 0.8 + 0.6 * len(main_rows)))
        ys = range(len(main_rows))
        ax.errorbar([r["estimate"] for r in main_rows], list(ys), xerr=[1.96 * r["std_error"] for r in main_rows],
                    fmt="o", color="#2457a6", ecolor="#2457a6", capsize=3)
        ax.axvline(0, color="#888", lw=1)
        ax.set_yticks(list(ys)); ax.set_yticklabels([f"{r['analysis_id']}: {r['outcome']}" for r in main_rows])
        ax.set_xlabel("Treatment effect (95% CI)")
        ax.spines[["top", "right"]].set_visible(False)
        fig.tight_layout(); fig.savefig(FIG / "registered_effects.png", dpi=150); plt.close(fig)
    print(f"wrote results/registered_summary.csv ({len(summary)} rows)")

if __name__ == "__main__":
    main()
