"""Deterministic script generation for the standard parts of the pipeline.

01_tidy.py      : raw export -> data/raw_tidy.csv (PII stripped) — reproduces the tidy stage.
02_clean.py     : raw_tidy -> data/clean.csv (exclusions, outcome construction, treat indicator).
03_registered.py: implemented hypotheses/subgroups -> results/*.csv + figures/registered_effects.png.

The LLM only writes code when a spec says kind == "custom".
"""
from __future__ import annotations

import json
from typing import Any

HEADER = '''"""{title}

Generated by filedrawer {version}. Run from the study folder: python scripts/{name}
"""
import json
import pathlib
import sys
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")
ROOT = pathlib.Path(__file__).resolve().parents[1]
'''


def render_tidy(raw_path_rel: str, drop_cols: list[str], qualtrics_header_rows: int, version: str) -> str:
    return HEADER.format(title="01_tidy: raw export -> data/raw_tidy.csv (identifier columns removed)",
                         version=version, name="01_tidy.py") + f'''
RAW = ROOT / {json.dumps(raw_path_rel)}
DROP = {json.dumps(drop_cols)}
SKIP = {json.dumps(list(range(1, qualtrics_header_rows)))}

def main():
    if not RAW.exists():
        print(f"raw export not found at {{RAW}}; data/raw_tidy.csv is the tidy copy shipped with this package")
        return
    df = pd.read_csv(RAW, skiprows=SKIP or None, dtype=str, keep_default_na=False, encoding="utf-8-sig")
    df = df[[c for c in df.columns if c not in DROP]]
    for c in df.columns:
        s = df[c].replace("", None)
        conv = pd.to_numeric(s, errors="coerce")
        df[c] = conv if s.notna().sum() > 0 and conv.notna().sum() == s.notna().sum() else s
    df.insert(0, "row_id", range(1, len(df) + 1))
    (ROOT / "data").mkdir(exist_ok=True)
    df.to_csv(ROOT / "data" / "raw_tidy.csv", index=False)
    print(f"wrote data/raw_tidy.csv: {{len(df)}} rows, {{df.shape[1]}} columns; dropped {{len(DROP)}} identifier columns")

if __name__ == "__main__":
    main()
'''


def render_clean(pap: dict, version: str) -> str:
    from ..pap import design_arms
    imp = pap["implemented"]
    design = pap.get("design", {})
    arms = design.get("arms", {}) or {}
    treated, control = design_arms(pap)
    return HEADER.format(title="02_clean: data/raw_tidy.csv -> data/clean.csv (exclusions, derived columns, outcomes, treatment indicator)",
                         version=version, name="02_clean.py") + f'''
OUTCOMES = json.loads({json.dumps(json.dumps(imp["outcomes"]))})
EXCLUSIONS = {json.dumps(imp.get("sample_exclusions", []))}
DERIVED = json.loads({json.dumps(json.dumps(design.get("derived") or {}))})
ARM_COL = {json.dumps(arms.get("column")) if arms.get("column") is not None else "None"}
TREATED = {json.dumps(treated)}            # list of treated arm values (strings)
CONTROL = {json.dumps(control) if control is not None else "None"}
ARM_LABELS = json.loads({json.dumps(json.dumps(arms.get("labels") or {}))})

def arm_str(v):
    """Canonical arm value: integral numbers (1, 1.0, "1.0") -> "1"."""
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return None
    sv = str(v).strip()
    try:
        f = float(sv)
    except ValueError:
        return sv
    return str(int(f)) if f.is_integer() else sv

def construct(df, o):
    kind = o.get("kind", "mean_items")
    lo, hi = o.get("scale") or [None, None]
    if kind == "single_item":
        return pd.to_numeric(df[o["columns"][0]], errors="coerce")
    if kind == "mean_items":
        parts = []
        for c in o["columns"]:
            s = pd.to_numeric(df[c], errors="coerce")
            if c in (o.get("reverse") or []) and lo is not None:
                s = (lo + hi) - s
            parts.append(s)
        return pd.concat(parts, axis=1).mean(axis=1, skipna=False)
    raise SystemExit(f"outcome {{o['name']}} has kind={{kind}}; custom construction must be implemented in this script")

def main():
    df = pd.read_csv(ROOT / "data" / "raw_tidy.csv")
    n0 = len(df)
    for expr in EXCLUSIONS:
        try:
            df = df.query(expr)
        except Exception as e:
            print(f"WARNING: exclusion {{expr!r}} could not be applied: {{e}}")
    print(f"sample: {{n0}} -> {{len(df)}} after exclusions {{EXCLUSIONS}}")
    for col, expr in DERIVED.items():
        try:
            df[col] = df.eval(expr)
        except Exception as e:
            raise SystemExit(f"derived column {{col!r}} = {{expr!r}} could not be computed: {{e}}")
        print(f"derived {{col}} = {{expr}}: mean={{pd.to_numeric(df[col], errors='coerce').mean():.3f}}")
    if ARM_COL and ARM_COL in df.columns:
        df["arm_code"] = df[ARM_COL].map(arm_str)
        keep = [a for a in TREATED + [CONTROL] if a is not None]
        df = df[df["arm_code"].isin(keep)].copy()
        df["treat"] = df["arm_code"].isin(TREATED).astype(int)
        df["arm"] = df["arm_code"].map(lambda a: ARM_LABELS.get(a, a))
        print(f"arms: {{df['arm_code'].value_counts().sort_index().to_dict()}}")
    for o in OUTCOMES:
        df[o["name"]] = construct(df, o)
        print(f"outcome {{o['name']}}: mean={{df[o['name']].mean():.3f}} sd={{df[o['name']].std():.3f}} missing={{int(df[o['name']].isna().sum())}}")
    (ROOT / "data").mkdir(exist_ok=True)
    df.to_csv(ROOT / "data" / "clean.csv", index=False)
    print(f"wrote data/clean.csv: {{len(df)}} rows, {{df.shape[1]}} columns")

if __name__ == "__main__":
    main()
'''


def render_registered(pap: dict, categorical: list[str], version: str) -> str:
    from ..pap import arm_label, hypothesis_arms, is_multiarm, is_pooled, words
    wd = words(pap)
    imp = pap["implemented"]
    std = [h for h in imp["hypotheses"] if h.get("estimator", {}).get("kind", "ols") != "custom"]
    multi = {}
    for h in std:
        if is_multiarm(h):
            arms, control = hypothesis_arms(h)
            multi[h["id"]] = {"arms": arms, "control": control, "labels": {a: arm_label(pap, a) for a in arms + [control]},
                              "pooled": is_pooled(h)}
    arm_col = (pap.get("design", {}).get("arms", {}) or {}).get("column")
    return HEADER.format(title="03_registered: registered (and documented-deviation) hypothesis tests",
                         version=version, name="03_registered.py") + f'''
import statsmodels.formula.api as smf
from scipy import stats as sps
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# Tufte-leaning figure style: ink on white, no chart junk, direct labels. Matches the dashboard palette.
INK, MUTED, RULE, ACCENT, POOL = "#1c1b19", "#8a877f", "#d9d5cc", "#8b1e2d", "#2f6f3e"
plt.rcParams.update({{"font.family": "sans-serif", "font.sans-serif": ["Inter", "Helvetica Neue", "Helvetica", "Arial", "DejaVu Sans"],
                     "font.size": 9.5, "axes.titlesize": 10.5, "axes.titleweight": "normal", "axes.titlelocation": "left",
                     "axes.labelsize": 9.5, "axes.labelcolor": INK, "xtick.labelsize": 8.5, "ytick.labelsize": 9,
                     "xtick.color": MUTED, "ytick.color": INK, "axes.edgecolor": RULE, "axes.linewidth": 0.8,
                     "figure.facecolor": "white", "axes.facecolor": "white", "savefig.facecolor": "white", "savefig.dpi": 200,
                     "axes.spines.top": False, "axes.spines.right": False, "axes.spines.left": False}})

def tufte(ax, zero=True):
    """Strip the frame, keep a light baseline, mark zero with a thin dashed rule."""
    ax.tick_params(axis="y", length=0)
    ax.tick_params(axis="x", length=3, width=0.6)
    ax.grid(False)
    if zero:
        ax.axvline(0, color=MUTED, lw=0.8, ls=(0, (3, 3)), zorder=1)
    ax.xaxis.set_major_locator(plt.MaxNLocator(5))

def fmt_est(e, lo, hi, d=3):
    return f"{{e:+.{{d}}f}}  [{{lo:+.{{d}}f}}, {{hi:+.{{d}}f}}]"

HYPOTHESES = json.loads({json.dumps(json.dumps(std))})
SUBGROUPS = json.loads({json.dumps(json.dumps(imp.get("subgroups", [])))})
MULTIARM = json.loads({json.dumps(json.dumps(multi))})     # hypothesis id -> {{arms, control, labels, pooled}}
OUTCOME_LABELS = json.loads({json.dumps(json.dumps({o["name"]: o.get("label") or o["name"] for o in imp.get("outcomes", [])}))})
CATEGORICAL = set({json.dumps(sorted(categorical))})
ARM_COL = {json.dumps(arm_col) if arm_col is not None else "None"}
FEATURES = json.loads({json.dumps(json.dumps(pap.get("design", {}).get("features") or []))})   # conjoint profile features
ALPHA = {json.dumps(imp.get("alpha", 0.05))}
WORDS = json.loads({json.dumps(json.dumps(wd))})     # design vocabulary: unit, reference, relation, estimate (pap.words)
RES = ROOT / "results"; FIG = ROOT / "figures"
RES.mkdir(exist_ok=True); FIG.mkdir(exist_ok=True)

def arm_str(v):
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return None
    sv = str(v).strip()
    try:
        f = float(sv)
    except ValueError:
        return sv
    return str(int(f)) if f.is_integer() else sv

def cat_set(est):
    """Categorical covariates for one hypothesis: codebook-labelled columns, plus estimator.categorical,
    minus estimator.continuous (lets a plan pin an ordinal item as continuous, as the original model did)."""
    return (CATEGORICAL | set(est.get("categorical") or [])) - set(est.get("continuous") or [])

def term(c, cats=CATEGORICAL):
    return f"C({{c}})" if c in cats else c

def fit(df, formula, est):
    kw = {{}}
    cl = est.get("cluster")
    if cl:
        kw = dict(cov_type="cluster", cov_kwds={{"groups": df[cl]}})
    else:
        kw = dict(cov_type=est.get("robust") or "HC2")
    w = est.get("weights")
    model = smf.wls(formula, data=df, weights=df[w]) if w else smf.ols(formula, data=df)
    return model.fit(**kw)

def centered(d, covs, cats=CATEGORICAL):
    """Lin (2013): covariates centred at their sample means; categorical covariates become centred dummies.
    Returns (data, list of centred column names)."""
    cols = []
    for c in covs:
        if c in cats:
            dums = pd.get_dummies(d[c].astype(str), prefix=c, drop_first=True, dtype=float)
            for k in dums.columns:
                name = "".join(ch if ch.isalnum() else "_" for ch in k) + "_c"
                d[name] = dums[k] - dums[k].mean()
                cols.append(name)
        else:
            d[c + "_c"] = pd.to_numeric(d[c], errors="coerce") - pd.to_numeric(d[c], errors="coerce").mean()
            cols.append(c + "_c")
    return d, cols

def build_formula(y, est, covs, d, arm_term="treat"):
    kind = est.get("kind", "ols")
    fe = "".join(f" + C({{c}})" for c in (est.get("absorb") or []))      # fixed effects
    cats = cat_set(est)
    if kind == "did":
        # difference in differences: the treat x post interaction is the estimate
        return f"{{y}} ~ {{arm_term}} * post" + "".join(f" + {{term(c, cats)}}" for c in covs) + fe, d
    if kind == "diff_means" or not covs:
        return f"{{y}} ~ {{arm_term}}" + fe, d
    if kind == "lin":
        d, cc = centered(d, covs, cats)
        return f"{{y}} ~ {{arm_term}} * ({{' + '.join(cc)}})" + fe, d
    return f"{{y}} ~ {{arm_term}}" + "".join(f" + {{term(c, cats)}}" for c in covs) + fe, d

def tidy(res, analysis_id):
    ci = res.conf_int()
    rows = []
    for t in res.params.index:
        rows.append({{"analysis_id": analysis_id, "term": t, "estimate": res.params[t], "std_error": res.bse[t],
                     "statistic": res.tvalues[t], "p_value": res.pvalues[t], "conf_low": ci.loc[t, 0], "conf_high": ci.loc[t, 1]}})
    return pd.DataFrame(rows)

def directional_p(est, p, direction):
    """p-value matching the hypothesis: one-sided for a stated direction (half the two-sided p when the
    estimate has the predicted sign, 1 - p/2 otherwise), two-sided otherwise."""
    if direction == "positive":
        return float(p / 2 if est > 0 else 1 - p / 2)
    if direction == "negative":
        return float(p / 2 if est < 0 else 1 - p / 2)
    return float(p)

def supported(est, p, direction):
    return bool(directional_p(est, p, direction) < ALPHA)

def pool(effects, variances):
    """Random-effects pooled estimate (iterated tau^2; DerSimonian-Laird fallback).
    The arm effects share one control group, so they are not independent: the pooled SE is approximate."""
    from statsmodels.stats.meta_analysis import combine_effects
    eff, var = np.asarray(effects, float), np.asarray(variances, float)
    try:
        cr = combine_effects(eff, var, method_re="iterated")
        if not np.isfinite(cr.tau2):
            raise ValueError("tau2 not finite")
        method = "iterated"
    except Exception:
        cr = combine_effects(eff, var, method_re="dl")
        method = "dl"
    est, se = float(cr.mean_effect_re), float(cr.sd_eff_w_re)
    p = float(2 * sps.norm.sf(abs(est / se))) if se > 0 else float("nan")
    i2 = float(max(0.0, min(1.0, cr.i2))) if np.isfinite(cr.i2) else float("nan")
    return {{"estimate": est, "std_error": se, "p_value": p, "tau2": float(cr.tau2), "i2": i2, "method": method,
            "conf_low": est - 1.96 * se, "conf_high": est + 1.96 * se}}

def forest(hid, arms_df, pooled, outcome):
    """One row per arm, sorted by estimate; dot + thin 95% CI; estimate printed at the right margin;
    pooled estimate as a diamond on its own row below a hairline."""
    a = arms_df.sort_values("estimate", ascending=True).reset_index(drop=True)
    k = len(a)
    extra = 1 if pooled is not None else 0
    fig, ax = plt.subplots(figsize=(7.4, 1.3 + 0.36 * (k + extra)))
    ys = np.arange(k) + (1.6 if pooled is not None else 0.5)
    # filled = two-sided p < ALPHA, so a filled dot always has a 95% CI that excludes zero
    for y, (e, lo, hi, p) in zip(ys, zip(a["estimate"], a["conf_low"], a["conf_high"], a["p_value"])):
        ax.plot([lo, hi], [y, y], color=INK, lw=1.0, solid_capstyle="butt", zorder=2)
        ax.plot(e, y, "o", ms=5, color=INK if p < ALPHA else "white", markeredgecolor=INK, markeredgewidth=1.0, zorder=3)
    labels = [f"{{l}}  (n = {{int(n)}})" for l, n in zip(a["arm_label"], a["n_arm"])]
    ticks = list(ys)
    xmin = min(a["conf_low"].min(), pooled["conf_low"] if pooled is not None else 0, 0)
    xmax = max(a["conf_high"].max(), pooled["conf_high"] if pooled is not None else 0, 0)
    span = xmax - xmin
    for y, (e, lo, hi) in zip(ys, zip(a["estimate"], a["conf_low"], a["conf_high"])):
        ax.text(xmax + 0.06 * span, y, fmt_est(e, lo, hi), va="center", ha="left", fontsize=8, color=MUTED, family="monospace")
    if pooled is not None:
        y0 = 0.5
        ax.axhline(1.05, color=RULE, lw=0.6)
        ax.plot([pooled["conf_low"], pooled["conf_high"]], [y0, y0], color=POOL, lw=1.2, zorder=2)
        ax.plot(pooled["estimate"], y0, "D", ms=5.5, color=POOL, zorder=3)
        ax.text(xmax + 0.06 * span, y0, fmt_est(pooled["estimate"], pooled["conf_low"], pooled["conf_high"]),
                va="center", ha="left", fontsize=8, color=POOL, family="monospace")
        ticks = [y0] + ticks; labels = ["Pooled, random effects"] + labels
    ax.set_yticks(ticks); ax.set_yticklabels(labels)
    ax.set_xlim(xmin - 0.04 * span, xmax + 0.42 * span)
    ax.set_ylim(-0.2, ys[-1] + 0.8)
    label = OUTCOME_LABELS.get(outcome, outcome)
    ax.set_xlabel(f"{{WORDS['relation'].capitalize()}} on {{label.lower()}}, relative to the {{WORDS['reference']}} (95% CI).\\nFilled dots: two-sided p < {{ALPHA}}.")
    ax.set_title(f"{{hid}}. {{WORDS['relation'].capitalize()}} of each {{WORDS['unit']}} on {{label.lower()}}")
    tufte(ax)
    fig.tight_layout(); fig.savefig(FIG / f"{{hid}}_arms.png", bbox_inches="tight", pad_inches=0.15); plt.close(fig)

def run_multiarm(h, d, est, covs):
    spec = MULTIARM[h["id"]]
    arms, control = spec["arms"], spec["control"]
    y = h["outcome"]
    d = d.copy()
    d["arm_code"] = d["arm_code"].map(arm_str)
    d = d[d["arm_code"].isin(arms + [control])]
    extra = [c for c in (est.get("weights"), est.get("cluster")) if c]
    eligible = d["arm_code"].value_counts()
    n_eligible = int(len(d))
    d = d.dropna(subset=[y, "arm_code"] + covs + extra)
    if n_eligible - len(d):
        print(f"{{h['id']}}: dropped {{n_eligible - len(d)}} of {{n_eligible}} eligible rows with a missing outcome, covariate, weight or cluster value")
    arm_term = f"C(arm_code, Treatment(reference={{control!r}}))"
    formula, d = build_formula(y, est, covs, d, arm_term)
    res = fit(d, formula, est)
    tidy(res, h["id"]).to_csv(RES / f"{{h['id']}}.csv", index=False)
    ci = res.conf_int()
    mean_control = d.loc[d["arm_code"] == control, y].mean()
    direction = h.get("direction", "two_sided")
    rows, summary = [], []
    for a in arms:
        t = f"{{arm_term}}[T.{{a}}]"
        if t not in res.params.index:
            print(f"WARNING: {{h['id']}} arm {{a}} has no coefficient (no observations?)")
            continue
        e, se, p = float(res.params[t]), float(res.bse[t]), float(res.pvalues[t])
        n_arm = int((d["arm_code"] == a).sum())
        rows.append({{"analysis_id": f"{{h['id']}}:{{a}}", "arm_code": a, "arm_label": spec["labels"].get(a, a), "estimate": e,
                     "std_error": se, "p_value": p, "conf_low": float(ci.loc[t, 0]), "conf_high": float(ci.loc[t, 1]),
                     "n_arm": n_arm, "n_arm_eligible": int(eligible.get(a, 0)), "mean_control": mean_control,
                     "mean_arm": d.loc[d["arm_code"] == a, y].mean(), "p_directional": directional_p(e, p, direction),
                     "supported": supported(e, p, direction)}})
        summary.append({{"analysis_id": f"{{h['id']}}:{{a}}", "outcome": y, "formula": formula, "cov_type": res.cov_type,
                        "estimate": e, "std_error": se, "p_value": p, "n": int(res.nobs),
                        "mean_control": mean_control, "mean_treated": rows[-1]["mean_arm"], "direction": direction,
                        "p_directional": directional_p(e, p, direction), "n_eligible": n_eligible,
                        "n_control": int((d["arm_code"] == control).sum()),
                        "supported": rows[-1]["supported"], "term": t, "arm": a, "weights": est.get("weights") or ""}})
    arms_df = pd.DataFrame(rows)
    arms_df.to_csv(RES / f"{{h['id']}}_arms.csv", index=False)
    pooled = None
    if spec.get("pooled", True) and len(arms_df) >= 2:
        pooled = pool(arms_df["estimate"], arms_df["std_error"] ** 2)
        summary.append({{"analysis_id": f"{{h['id']}}:pooled", "outcome": y, "formula": formula, "cov_type": res.cov_type,
                        "estimate": pooled["estimate"], "std_error": pooled["std_error"], "p_value": pooled["p_value"], "n": int(res.nobs),
                        "mean_control": mean_control, "mean_treated": d.loc[d["arm_code"] != control, y].mean(), "direction": direction,
                        "p_directional": directional_p(pooled["estimate"], pooled["p_value"], direction), "n_eligible": n_eligible,
                        "n_control": int((d["arm_code"] == control).sum()),
                        "supported": supported(pooled["estimate"], pooled["p_value"], direction), "arm": "pooled",
                        "weights": est.get("weights") or "", "tau2": pooled["tau2"], "i2": pooled["i2"], "pooled_method": pooled["method"],
                        "k_arms": int(len(arms_df))}})
    forest(h["id"], arms_df, pooled, y)
    n_sig = int(arms_df["supported"].sum()) if len(arms_df) else 0
    print(f"{{h['id']}}: {{formula}} | {{len(arms_df)}} arms vs {{spec['labels'].get(control, control)}}, N={{int(res.nobs)}}, "
          f"{{res.cov_type}} SEs{{', weights=' + est['weights'] if est.get('weights') else ''}}; {{n_sig}} arm(s) supported"
          + (f"; pooled={{pooled['estimate']:.3f}} (SE {{pooled['std_error']:.3f}}, p={{pooled['p_value']:.4f}}, tau2={{pooled['tau2']:.4f}}, I2={{pooled['i2']:.2f}})" if pooled else ""))
    return summary

def prep_treatment(h, d):
    """Set the treatment for one hypothesis. A hypothesis may name its own treatment column (a conjoint
    feature, or any categorical column), which then replaces the design arms; with treatment.continuous the
    column enters as a numeric slope. Two-arm contrasts restrict the data to the two contrasted values."""
    t = h.get("treatment") or {{}}
    col = t.get("column")
    if col and col in d.columns:
        if t.get("continuous"):
            d = d.copy()
            d["treat"] = pd.to_numeric(d[col], errors="coerce")
            return d
        if col != ARM_COL:
            d = d.copy()
            d["arm_code"] = d[col].map(arm_str)
    contrast = [arm_str(x) for x in (t.get("contrast") or [])]
    collapse = [arm_str(x) for x in (t.get("collapse_from") or [])]
    if collapse and len(contrast) == 2 and "arm_code" in d.columns:
        # robustness addendum: every treated arm pooled into one indicator against the control arm
        codes = d["arm_code"].map(arm_str)
        d = d[codes.isin(collapse + [contrast[1]])].copy()
        d["treat"] = d["arm_code"].map(arm_str).isin(collapse).astype(int)
    elif len(contrast) == 2 and "arm_code" in d.columns:
        # restrict to the two contrasted arms (a no-op in a two-arm design)
        codes = d["arm_code"].map(arm_str)
        d = d[codes.isin(contrast)].copy()
        d["treat"] = (d["arm_code"].map(arm_str) == contrast[0]).astype(int)
    est = h.get("estimator") or {{}}
    if est.get("kind") == "did":                     # the post-period indicator for a difference in differences
        d = d.copy()
        d["post"] = pd.to_numeric(d[est["period"]], errors="coerce")
    return d

def subgroup_multiarm(s, h, d, est, covs):
    """Heterogeneity for a multi-arm (or conjoint-feature) hypothesis. estimand "mm_diff": marginal means of
    every level in the two moderator groups and their difference (second level minus first), from a cell-means
    model with the hypothesis's standard errors (covariates do not enter marginal means). Otherwise
    ("effect_by"): the hypothesis's arm effects within each moderator level, plus arm x moderator interactions."""
    spec = MULTIARM[h["id"]]
    arms, control = spec["arms"], spec["control"]
    y = h["outcome"]
    extra = [c for c in (est.get("weights"), est.get("cluster")) if c]
    levels = s.get("levels") or {{}}
    lab = lambda a: spec["labels"].get(a, a)
    rows, out = [], []
    if s.get("estimand") == "mm_diff":
        # every level of every listed feature (default: the hypothesis's own treatment column); each feature's
        # marginal means use the rows where that feature, the outcome and the moderator are observed (as cregg does)
        feats = s.get("features") or [(h.get("treatment") or {{}}).get("column")]
        d = d.dropna(subset=[y, "_mod"] + extra).copy()
        order = [v for v in dict.fromkeys(levels.values()) if v in set(d["_mod"])] if levels else sorted(d["_mod"].unique())
        if len(order) != 2:
            raise SystemExit(f"{{s['id']}}: mm_diff needs exactly two moderator levels, found {{order}}")
        lo, hi = order
        for f in feats:
            df_ = d.dropna(subset=[f]).copy()
            codes = df_[f].map(arm_str)
            df_["_cell"] = codes + " @ " + df_["_mod"]
            res = fit(df_, f"{{y}} ~ 0 + C(_cell)", est)
            names = list(res.params.index)
            for a in sorted(codes.dropna().unique()):
                tl, th = f"C(_cell)[{{a}} @ {{lo}}]", f"C(_cell)[{{a}} @ {{hi}}]"
                if tl not in names or th not in names:
                    continue
                c = np.zeros(len(names)); c[names.index(th)] = 1.0; c[names.index(tl)] = -1.0
                tt = res.t_test(c)
                e, se, p = float(np.squeeze(tt.effect)), float(np.squeeze(tt.sd)), float(np.squeeze(tt.pvalue))
                rows.append({{"analysis_id": s["id"], "feature": f, "level": lab(a), f"mm_{{lo}}": float(res.params[tl]),
                             f"mm_{{hi}}": float(res.params[th]), "difference": e, "std_error": se, "p_value": p,
                             "n_" + str(lo): int(((codes == a) & (df_["_mod"] == lo)).sum()),
                             "n_" + str(hi): int(((codes == a) & (df_["_mod"] == hi)).sum())}})
                out.append({{"analysis_id": f"{{s['id']}}:{{f}}={{a}}", "outcome": y, "formula": f"{{y}} ~ 0 + {{f}} x {{s['moderator']}} cells",
                            "cov_type": res.cov_type, "estimate": e, "std_error": se, "p_value": p, "n": int(res.nobs),
                            "mean_control": np.nan, "mean_treated": np.nan, "direction": "two_sided",
                            "supported": bool(p < ALPHA), "term": f"MM difference {{hi}} - {{lo}}: {{lab(a)}}", "arm": ""}})
                print(f"{{s['id']}}: {{f}}={{lab(a)}} MM {{hi}} - {{lo}} = {{e:+.3f}} (SE {{se:.3f}}, p={{p:.4f}})")
        pd.DataFrame(rows).to_csv(RES / f"{{s['id']}}_by_level.csv", index=False)
        return out
    d = d.copy()
    d["arm_code"] = d["arm_code"].map(arm_str)
    d = d[d["arm_code"].isin(arms + [control])]
    d = d.dropna(subset=[y, "arm_code", "_mod"] + covs + extra)
    order = [v for v in dict.fromkeys(levels.values()) if v in set(d["_mod"])] if levels else sorted(d["_mod"].unique())
    arm_term = f"C(arm_code, Treatment(reference={{control!r}}))"
    cats = cat_set(est)
    cov_terms = "".join(f" + {{term(c, cats)}}" for c in covs)
    res = fit(d, f"{{y}} ~ {{arm_term}} * C(_mod){{cov_terms}}", est)
    for lvl in order:
        sub = d[d["_mod"] == lvl]
        r = fit(sub, f"{{y}} ~ {{arm_term}}{{cov_terms}}", est)
        ci = r.conf_int()
        for a in arms:
            t = f"{{arm_term}}[T.{{a}}]"
            if t in r.params.index:
                rows.append({{"analysis_id": s["id"], "level": lvl, "arm": lab(a), "estimate": float(r.params[t]),
                             "std_error": float(r.bse[t]), "p_value": float(r.pvalues[t]),
                             "conf_low": float(ci.loc[t, 0]), "conf_high": float(ci.loc[t, 1]), "n": int(r.nobs)}})
    for t in res.params.index:
        if ":C(_mod)" not in t or "arm_code" not in t:
            continue
        a = t.split("[T.", 1)[1].split("]", 1)[0]
        m = t.rsplit("[T.", 1)[1].rstrip("]")
        out.append({{"analysis_id": s["id"], "outcome": y, "formula": f"{{y}} ~ arms x {{s['moderator']}}" + cov_terms,
                    "cov_type": res.cov_type, "estimate": float(res.params[t]), "std_error": float(res.bse[t]),
                    "p_value": float(res.pvalues[t]), "n": int(res.nobs), "mean_control": np.nan, "mean_treated": np.nan,
                    "direction": "two_sided", "supported": bool(res.pvalues[t] < ALPHA),
                    "term": f"{{lab(a)}} x {{m}} (vs {{order[0]}})", "arm": ""}})
        print(f"{{s['id']}}: interaction {{lab(a)}} x {{m}} = {{res.params[t]:.3f}} (SE {{res.bse[t]:.3f}}, p={{res.pvalues[t]:.4f}})")
    pd.DataFrame(rows).to_csv(RES / f"{{s['id']}}_by_level.csv", index=False)
    return out

def amce_figures(summary):
    """Conjoint: one figure per outcome with every feature's levels (reference level at zero, hollow), grouped by
    feature in design order, from the unweighted per-feature hypotheses."""
    by_col = {{f["column"]: f for f in FEATURES}}
    rows = {{r["analysis_id"]: r for r in summary if r.get("arm") not in (None, "", "pooled")}}
    for outcome in dict.fromkeys(h["outcome"] for h in HYPOTHESES):
        hs = [h for h in HYPOTHESES if h["outcome"] == outcome and h["id"] in MULTIARM and not h.get("estimator", {{}}).get("weights")
              and (h.get("treatment") or {{}}).get("column") in by_col]
        if len(hs) < 2:
            continue
        hs.sort(key=lambda h: list(by_col).index(h["treatment"]["column"]))
        items = []                                   # (label, estimate, lo, hi, is_reference, is_header)
        for h in hs:
            f = by_col[h["treatment"]["column"]]
            spec = MULTIARM[h["id"]]
            items.append((f.get("label", f["column"]), None, None, None, False, True))
            for lvl in [spec["control"]] + spec["arms"]:
                if lvl == spec["control"]:
                    items.append((spec["labels"].get(lvl, lvl), 0.0, 0.0, 0.0, True, False))
                    continue
                r = rows.get(f"{{h['id']}}:{{lvl}}")
                if r:
                    e, se = float(r["estimate"]), float(r["std_error"])
                    items.append((spec["labels"].get(lvl, lvl), e, e - 1.96 * se, e + 1.96 * se, False, False))
        fig, ax = plt.subplots(figsize=(7.4, 0.8 + 0.26 * len(items)))
        ys = list(range(len(items)))[::-1]
        lo_all = min([i[2] for i in items if i[2] is not None] + [0]); hi_all = max([i[3] for i in items if i[3] is not None] + [0])
        for y, (lab, e, lo, hi, ref, head) in zip(ys, items):
            if head:
                continue
            if ref:
                ax.plot(0, y, "o", ms=4.5, color="white", markeredgecolor=MUTED, zorder=3)
                continue
            sig = lo > 0 or hi < 0
            ax.plot([lo, hi], [y, y], color=ACCENT if sig else INK, lw=1.0, zorder=2)
            ax.plot(e, y, "o", ms=5, color=ACCENT if sig else INK, zorder=3)
        ax.set_yticks(ys)
        ax.set_yticklabels([("" if head else "   ") + lab for (lab, *_rest, head) in items])
        for tick, it in zip(ax.get_yticklabels(), items):
            if it[5]:
                tick.set_fontweight("bold")
        span = (hi_all - lo_all) or 1.0
        ax.set_xlim(lo_all - 0.06 * span, hi_all + 0.06 * span)
        ax.set_xlabel(f"Change in Pr(chosen) relative to the reference level (hollow), 95% CI. Red: CI excludes 0.")
        ax.set_title(f"AMCEs on {{outcome}}")
        tufte(ax)
        fig.tight_layout(); fig.savefig(FIG / f"amce_{{outcome}}.png"); plt.close(fig)

def reestimate(h, d, moderator=None):
    """Re-fit one hypothesis's specification (its exclusions, treatment coding, covariates and centring, weights
    and standard errors) on the data d, writing nothing. h is a hypothesis id or dict. Returns one row per
    treatment effect (columns term, arm, estimate, std_error, p_value, conf_low, conf_high, n). With moderator
    (a column of d), returns the treatment x moderator interactions instead: one centred slope per arm for a
    numeric moderator with more than two values, one row per level otherwise (text or 0/1 columns; bin a numeric
    moderator first to compare groups). Covariates other than the moderator then enter additively. Used by exploratory robustness and heterogeneity checks."""
    if isinstance(h, str):
        h = {{x["id"]: x for x in HYPOTHESES}}[h]
    d = d.copy()
    for expr in h.get("exclusions") or []:
        try:
            d = d.query(expr)
        except Exception:
            pass
    est = h.get("estimator") or {{}}
    y = h["outcome"]
    covs = [c for c in (est.get("covariates") or []) if c != y]      # a covariate used as a placebo outcome leaves the model
    d = prep_treatment(h, d)
    extra = [c for c in (est.get("weights"), est.get("cluster")) if c] + (["post"] if est.get("kind") == "did" else [])
    if h["id"] in MULTIARM:
        spec = MULTIARM[h["id"]]
        d["arm_code"] = d["arm_code"].map(arm_str)
        d = d[d["arm_code"].isin(spec["arms"] + [spec["control"]])]
        arm_term, tcol = f"C(arm_code, Treatment(reference={{spec['control']!r}}))", "arm_code"
        keys = [(f"{{arm_term}}[T.{{a}}]", spec["labels"].get(a, a)) for a in spec["arms"]]
    else:
        arm_term, tcol = "treat", "treat"
        keys = [("treat:post" if est.get("kind") == "did" and moderator is None else "treat", "treat")]
    if moderator is None:
        d = d.dropna(subset=[y, tcol] + covs + extra)
        formula, d = build_formula(y, est, covs, d, arm_term)
        match = lambda t, k: t == k
    else:
        covs = [c for c in covs if c != moderator]
        d = d.dropna(subset=[y, tcol, moderator] + covs + extra)
        m = pd.to_numeric(d[moderator], errors="coerce")
        if m.notna().all() and m.nunique() > 2:
            d["_mod"], mterm = m - m.mean(), "_mod"
        else:
            d["_mod"], mterm = d[moderator].map(arm_str), "C(_mod)"
        formula = f"{{y}} ~ {{arm_term}} * {{mterm}}" + "".join(f" + {{term(c, cat_set(est))}}" for c in covs)
        match = lambda t, k: t.startswith(k + ":" + mterm)
    res = fit(d, formula, est)
    ci = res.conf_int()
    rows = []
    hits = [(t, lab) for k, lab in keys for t in res.params.index if match(t, k)]    # arms in plan order
    for t, lab in hits:
        name = lab if moderator is None else f"{{lab}} x {{moderator}}" + (f"={{t.rsplit('[T.', 1)[1].rstrip(']')}}" if "[T." in t.split(":", 1)[-1] else "")
        rows.append({{"term": t, "arm": name, "estimate": float(res.params[t]), "std_error": float(res.bse[t]),
                     "p_value": float(res.pvalues[t]), "conf_low": float(ci.loc[t, 0]), "conf_high": float(ci.loc[t, 1]),
                     "n": int(res.nobs)}})
    return pd.DataFrame(rows, columns=["term", "arm", "estimate", "std_error", "p_value", "conf_low", "conf_high", "n"])

def main():
    df = pd.read_csv(ROOT / "data" / "clean.csv")
    summary = []
    for h in HYPOTHESES:
        d = df.copy()
        for expr in h.get("exclusions") or []:
            try:
                d = d.query(expr)
            except Exception as e:
                print(f"WARNING: {{h['id']}} exclusion {{expr!r}} skipped: {{e}}")
        est = h.get("estimator", {{}})
        covs = est.get("covariates") or []
        d = prep_treatment(h, d)
        if h["id"] in MULTIARM:
            summary += run_multiarm(h, d, est, covs)
            continue
        continuous = bool((h.get("treatment") or {{}}).get("continuous"))
        if "treat" not in d.columns:
            raise SystemExit(f"{{h['id']}}: no treatment indicator could be built. Set design.arms (a column with treated "
                             f"and control values), or give the hypothesis a treatment.column with a two-value contrast, "
                             f"arms + control, or continuous: true.")
        extra = [c for c in (est.get("weights"), est.get("cluster")) if c] + (["post"] if est.get("kind") == "did" else [])
        n_eligible = int(len(d))
        d = d.dropna(subset=[h["outcome"], "treat"] + covs + extra)
        if n_eligible - len(d):
            print(f"{{h['id']}}: dropped {{n_eligible - len(d)}} of {{n_eligible}} eligible rows with a missing outcome, covariate, weight or cluster value")
        formula, d = build_formula(h["outcome"], est, covs, d)
        res = fit(d, formula, est)
        tidy(res, h["id"]).to_csv(RES / f"{{h['id']}}.csv", index=False)
        coef = "treat:post" if est.get("kind") == "did" else "treat"
        e, se, p = res.params[coef], res.bse[coef], res.pvalues[coef]
        g = d.groupby("treat")[h["outcome"]].agg(["mean", "std", "count"])
        row = {{"analysis_id": h["id"], "outcome": h["outcome"], "formula": formula, "cov_type": res.cov_type,
               "estimate": e, "std_error": se, "p_value": p, "n": int(res.nobs),
               "mean_control": g.loc[0, "mean"] if 0 in g.index and not continuous else np.nan,
               "mean_treated": g.loc[1, "mean"] if 1 in g.index and not continuous else np.nan,
               "direction": h.get("direction", "two_sided"), "p_directional": directional_p(e, p, h.get("direction", "two_sided")),
               "n_eligible": n_eligible, "supported": supported(e, p, h.get("direction", "two_sided"))}}
        if est.get("weights"):
            row["weights"] = est["weights"]
        if continuous:
            row["continuous"] = True
        summary.append(row)
        print(f"{{h['id']}}: {{formula}} | ATE={{e:.3f}} (SE {{se:.3f}}, p={{p:.4f}}, N={{int(res.nobs)}})")
    hyps = {{h["id"]: h for h in HYPOTHESES}}
    for s in SUBGROUPS:
        h = hyps.get(s["hypothesis"])
        if h is None:
            continue
        d = df.copy()
        for expr in h.get("exclusions") or []:
            try:
                d = d.query(expr)
            except Exception:
                pass
        levels = s.get("levels") or {{}}
        mod = s["moderator"]
        d = prep_treatment(h, d)
        if levels:
            d = d[d[mod].map(arm_str).isin([arm_str(k) for k in levels])]
        _est = h.get("estimator", {{}})
        scovs = [c for c in (_est.get("covariates") or []) if c != mod] if s.get("covariates") else []
        d["_mod"] = d[mod].map(arm_str).map({{arm_str(k): v for k, v in levels.items()}}) if levels else d[mod].map(arm_str)
        if h["id"] in MULTIARM:
            summary += subgroup_multiarm(s, h, d, _est, scovs)
            continue
        d = d.dropna(subset=[h["outcome"], "treat", "_mod"] + scovs + [c for c in (_est.get("weights"), _est.get("cluster")) if c])
        sterms = "".join(f" + {{term(c, cat_set(_est))}}" for c in scovs)
        res = fit(d, f"{{h['outcome']}} ~ treat * C(_mod){{sterms}}", h.get("estimator", {{}}))
        tidy(res, s["id"]).to_csv(RES / f"{{s['id']}}.csv", index=False)
        inter = [t for t in res.params.index if t.startswith("treat:")]
        rows = []
        for lvl, sub in d.groupby("_mod"):
            r = fit(sub, f"{{h['outcome']}} ~ treat{{sterms}}", h.get("estimator", {{}}))
            rows.append({{"analysis_id": s["id"], "level": lvl, "estimate": r.params["treat"], "std_error": r.bse["treat"],
                         "p_value": r.pvalues["treat"], "n": int(r.nobs)}})
        pd.DataFrame(rows).to_csv(RES / f"{{s['id']}}_by_level.csv", index=False)
        ref = sorted(d["_mod"].unique())[0]
        tname = (h.get("treatment") or {{}}).get("column") or "treatment"
        for t in inter:
            lvl = t.rsplit("[T.", 1)[1].rstrip("]") if "[T." in t else t
            summary.append({{"analysis_id": s["id"], "outcome": h["outcome"], "formula": f"{{h['outcome']}} ~ treat * C({{mod}})",
                            "cov_type": res.cov_type, "estimate": res.params[t], "std_error": res.bse[t], "p_value": res.pvalues[t],
                            "n": int(res.nobs), "mean_control": np.nan, "mean_treated": np.nan, "direction": "two_sided",
                            "supported": bool(res.pvalues[t] < ALPHA), "term": f"{{tname}} x {{lvl}} (vs {{ref}})"}})
            print(f"{{s['id']}}: interaction {{tname}} x {{lvl}} (vs {{ref}}) = {{res.params[t]:.3f}} (SE {{res.bse[t]:.3f}}, p={{res.pvalues[t]:.4f}})")
    pd.DataFrame(summary).to_csv(RES / "registered_summary.csv", index=False)
    if FEATURES:
        amce_figures(summary)
    # coefficient plot: one row per two-arm hypothesis and per pooled multi-arm estimate
    main_rows = [r for r in summary if "term" not in r]
    if main_rows:
        fig, ax = plt.subplots(figsize=(7.4, 1.2 + 0.42 * len(main_rows)))
        ys = list(range(len(main_rows)))
        ests = [float(r["estimate"]) for r in main_rows]; ses = [float(r["std_error"]) for r in main_rows]
        los = [e - 1.96 * se for e, se in zip(ests, ses)]; his = [e + 1.96 * se for e, se in zip(ests, ses)]
        xmin, xmax = min(los + [0]), max(his + [0]); span = (xmax - xmin) or 1.0
        for y, r, e, lo, hi in zip(ys, main_rows, ests, los, his):
            ax.plot([lo, hi], [y, y], color=INK, lw=1.0, zorder=2)
            ax.plot(e, y, "o", ms=5, color=INK if float(r["p_value"]) < ALPHA else "white", markeredgecolor=INK, zorder=3)
            ax.text(xmax + 0.06 * span, y, fmt_est(e, lo, hi), va="center", ha="left", fontsize=8, color=MUTED, family="monospace")
        ax.set_yticks(ys); ax.set_yticklabels([f"{{r['analysis_id']}}: {{OUTCOME_LABELS.get(r['outcome'], r['outcome'])}}" for r in main_rows])
        ax.set_xlim(xmin - 0.04 * span, xmax + 0.42 * span)
        ax.set_xlabel(f"{{WORDS['estimate'].capitalize()}} (95% CI). Filled dots: two-sided p < {{ALPHA}}.")
        ax.set_title(f"Planned {{WORDS['estimates']}}")
        tufte(ax)
        fig.tight_layout(); fig.savefig(FIG / "registered_effects.png", bbox_inches="tight", pad_inches=0.15); plt.close(fig)
    print(f"wrote results/registered_summary.csv ({{len(summary)}} rows)")

if __name__ == "__main__":
    main()
'''
